### ISSUE TITLE
Doesnt work in API 19

### ISSUE THREAD

**Issue by M9Apar** [lj-3d/GearLoadingProject#1]
Hi its facing crash in API 19 below is the logcat,
  Process: lj_3d.gearloadingproject, PID: 19716
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{lj_3d.gearloadingproject/lj_3d.gearloadingproject.PullToRefreshActivity}: java.lang.NullPointerException
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
                                                       at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
                                                       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
                                                       at android.animation.ValueAnimator.start(ValueAnimator.java:936)
                                                       at android.animation.ValueAnimator.start(ValueAnimator.java:946)
                                                       at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
                                                       at lj_3d.gearloadinglayout.gearViews.GearView.startSpinning(GearView.java:125)
                                                       at lj_3d.gearloadinglayout.gearViews.TwoGearsLayout.start(TwoGearsLayout.java:52)
                                                       at lj_3d.gearloadingproject.PullToRefreshActivity.onCreate(PullToRefreshActivity.java:20)
                                                       at android.app.Activity.performCreate(Activity.java:5451)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:146) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by lj-3d** [comment]
Fixed. Try to pull changes and let me know if it works !!

2017-01-03 6:35 GMT+02:00 kaas3031 <notifications@github.com>:
